version: '3.3'

services:

  server:

    container_name: flask

    image: pmonteverdi/flaskexample:0.1

    build:

      context: ./flask

    ports:

      - 5000:5000

    env_file:

      - .env

    networks:

      - webnet
      


  nginx:

    container_name: nginx

    image: nginx:alpine
    
    restart: unless-stopped

    networks:

      - webnet

    ports: 

      - 80:80
      - 443:443

    volumes: 

      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

      - ./nginx/log/error.log:/var/log/nginx/error.log

      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    command: 
      
      "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      
    depends_on:

      - server


  certbot:
    
    container_name: certbot
    
    image: certbot/certbot
    
    restart: unless-stopped
    
    networks:

      - webnet

    volumes:
      
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    entrypoint: 

      "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
      
    depends_on:

      - nginx
    


networks:

  webnet:

volumes:

  data:
