version: '3.7'

services:

  commands:

    container_name: flask

    image: pmonteverdi/flaskexample:0.1

    build:

      context: ./flask

    ports:

      - 80:${SERVER_PORT}
      - 443:${SERVER_PORT}

    env_file:

      - .env

    networks:

      - webnet


  nginx:

    container_name: nginx

    image: nginx:alpine

    networks:

      - webnet

    ports: 

      - ${NGINX_PORT}:8080

    volumes: 

      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

      - ./nginx/log/error.log:/var/log/nginx/error.log

      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    command: 
      
      "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


  certbot:
    
    container_name: certbot
    
    image: certbot/certbot

    volumes:
      
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    entrypoint: 

      "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    


networks:

  webnet:

volumes:

  data: